### PR TITLE
Remove safe haskell

### PR DESCRIPTION
**Pull request by zliu41**
DerivingVia is no longer safe Haskell https://downloads.haskell.org/~ghc/9.0.2/docs/html/users_guide/9.0.2-notes.html

### CODE REVIEW

**Review by cmk — APPROVED** [review]

**Comment by cmk** [comment]
Thanks @zliu41. Look like my free Travis credits finally ran out. I just wrote them requesting OSS credits so give it a few days for them to respond.

**Comment by zliu41** [comment]
Perhaps use github actions instead of travis? The setup is fairly simple, e.g. https://github.com/con-kitty/categorifier/blob/master/.github/workflows/ci.yml

**Comment by zliu41** [comment]
I can open a PR for migrating to github actions if you want.

**Comment by cmk** [comment]
Sure that'd be great, thanks Ziyang.

**Comment by zliu41** [comment]
@cmk CI passed and this is ready to merge. The "properties (9.0.1)" task is obsolete and will be gone once merged

**Pull request merged**
